language: android

android:
    components:
        - build-tools-23.0.1
        - extra-android-m2repository
        - android-23

script:
    - ./gradlew assembleDebugAndroidTest test

after_success:
    - ./gradlew jacoco coveralls
