language: android

android:
    components:
        - build-tools-23.0.1
        - android-23
        - sys-img-armeabi-v7a-android-15
        - sys-img-armeabi-v7a-android-23

env:
    matrix:
        - ANDROID_TARGET=android-15 ANDROID_ABI=armeabi-v7a
        - ANDROID_TARGET=android-23 ANDROID_ABI=armeabi-v7a

script:
    - ./gradlew connectedDebugAndroidTest

after_script:
    - ./gradlew createDebugCoverageReport coveralls
